use std::borrow::Cow;
use std::fmt::Write as _;
use std::path::Path;

use smallvec::SmallVec;
use tracing::info;

use crate::config::Oobe;
use crate::error::{Error, write_file};

/// Generate and write an `autounattend.xml` file into the ISO staging directory.
///
/// This file is read by Windows Setup during installation to automate the
/// Out-of-Box Experience (OOBE), skipping Microsoft account requirements,
/// privacy consent screens, and other setup nags.
pub fn inject_autounattend(staging_dir: &Path, config: &Oobe) -> Result<(), Error> {
    if !config.inject_autounattend {
        return Ok(());
    }

    let xml = generate_autounattend(config);
    let dest = staging_dir.join("autounattend.xml");

    info!(path = %dest.display(), "injecting autounattend.xml into ISO root");

    write_file(&dest, &xml)?;

    Ok(())
}

fn generate_autounattend(config: &Oobe) -> String {
    let mut xml = String::new();

    xml.push_str(
        r#"<?xml version="1.0" encoding="utf-8"?>
<unattend xmlns="urn:schemas-microsoft-com:unattend" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State">
    <!--
        Generated by wincrab - debloated Windows 11 ISO builder.
        This file automates the Out-of-Box Experience (OOBE) to skip
        Microsoft account requirements, privacy screens, and setup nags.
    -->"#,
    );

    // -----------------------------------------------------------------------
    // windowsPE pass
    // -----------------------------------------------------------------------
    let has_windows_pe = config.skip_microsoft_account
        || config.bypass_tpm
        || config.bypass_secureboot
        || config.bypass_ram
        || config.disable_bitlocker
        || config.product_key.is_some()
        || config.auto_partition;

    if has_windows_pe {
        xml.push_str(
            r#"
    <settings pass="windowsPE">
        <component name="Microsoft-Windows-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">"#,
        );

        // -- RunSynchronous commands --
        // At most 5 built-in commands; SmallVec avoids heap allocation.
        let mut run_sync_cmds: SmallVec<[&str; 5]> = SmallVec::new();

        if config.skip_microsoft_account {
            run_sync_cmds.push(
                r#"reg add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OOBE /v BypassNRO /t REG_DWORD /d 1 /f"#,
            );
        }

        if config.bypass_tpm {
            run_sync_cmds.push(
                r#"reg add HKLM\SYSTEM\Setup\LabConfig /v BypassTPMCheck /t REG_DWORD /d 1 /f"#,
            );
        }

        if config.bypass_secureboot {
            run_sync_cmds.push(
                r#"reg add HKLM\SYSTEM\Setup\LabConfig /v BypassSecureBootCheck /t REG_DWORD /d 1 /f"#,
            );
        }

        if config.bypass_ram {
            run_sync_cmds.push(
                r#"reg add HKLM\SYSTEM\Setup\LabConfig /v BypassRAMCheck /t REG_DWORD /d 1 /f"#,
            );
        }

        if config.disable_bitlocker {
            run_sync_cmds.push(
                r#"reg add HKLM\SYSTEM\CurrentControlSet\Control\BitLocker /v PreventDeviceEncryption /t REG_DWORD /d 1 /f"#,
            );
        }

        if !run_sync_cmds.is_empty() {
            xml.push_str("\n            <RunSynchronous>");
            for (i, cmd) in run_sync_cmds.iter().enumerate() {
                let _ = write!(
                    xml,
                    r#"
                <RunSynchronousCommand wcm:action="add">
                    <Order>{}</Order>
                    <Path>{cmd}</Path>
                </RunSynchronousCommand>"#,
                    i + 1
                );
            }
            xml.push_str("\n            </RunSynchronous>");
        }

        // -- Product key --
        if let Some(ref key) = config.product_key {
            let _ = write!(
                xml,
                r#"
            <UserData>
                <ProductKey>
                    <Key>{key}</Key>
                </ProductKey>
            </UserData>"#
            );
        }

        // -- Auto partition --
        if config.auto_partition {
            xml.push_str(
                r#"
            <DiskConfiguration>
                <Disk wcm:action="add">
                    <DiskID>0</DiskID>
                    <WillWipeDisk>true</WillWipeDisk>
                    <CreatePartitions>
                        <CreatePartition wcm:action="add"><Order>1</Order><Size>300</Size><Type>EFI</Type></CreatePartition>
                        <CreatePartition wcm:action="add"><Order>2</Order><Size>16</Size><Type>MSR</Type></CreatePartition>
                        <CreatePartition wcm:action="add"><Order>3</Order><Extend>true</Extend><Type>Primary</Type></CreatePartition>
                    </CreatePartitions>
                </Disk>
            </DiskConfiguration>
            <ImageInstall>
                <OSImage>
                    <InstallTo><DiskID>0</DiskID><PartitionID>3</PartitionID></InstallTo>
                </OSImage>
            </ImageInstall>"#,
            );
        }

        xml.push_str(
            r#"
        </component>
    </settings>"#,
        );
    }

    // -----------------------------------------------------------------------
    // specialize pass
    // -----------------------------------------------------------------------
    let has_specialize =
        config.computer_name.is_some() || config.timezone.is_some() || config.skip_auto_activation;

    if has_specialize {
        xml.push_str(
            r#"
    <settings pass="specialize">"#,
        );

        if config.computer_name.is_some() || config.timezone.is_some() {
            xml.push_str(
                r#"
        <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">"#,
            );
            if let Some(ref name) = config.computer_name {
                let _ = write!(xml, "\n            <ComputerName>{name}</ComputerName>");
            }
            if let Some(ref tz) = config.timezone {
                let _ = write!(xml, "\n            <TimeZone>{tz}</TimeZone>");
            }
            xml.push_str(
                r#"
        </component>"#,
            );
        }

        if config.skip_auto_activation {
            xml.push_str(
                r#"
        <component name="Microsoft-Windows-Security-SPP-UX" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
            <SkipAutoActivation>true</SkipAutoActivation>
        </component>"#,
            );
        }

        xml.push_str(
            r#"
    </settings>"#,
        );
    }

    // -----------------------------------------------------------------------
    // oobeSystem pass
    // -----------------------------------------------------------------------
    xml.push_str(
        r#"
    <settings pass="oobeSystem">
        <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">"#,
    );

    // -- OOBE settings --
    // At most 5 static strings; write inline to avoid intermediate Vec + join.
    if config.skip_privacy_screens {
        xml.push_str(
            "\n            <OOBE>\
             \n                <ProtectYourPC>3</ProtectYourPC>\
             \n                <HideEULAPage>true</HideEULAPage>\
             \n                <HideWirelessSetupInOOBE>true</HideWirelessSetupInOOBE>\
             \n                <HideOnlineAccountScreens>true</HideOnlineAccountScreens>\
             \n                <HideOEMRegistrationScreen>true</HideOEMRegistrationScreen>\
             \n            </OOBE>",
        );
    }

    // -- Local account --
    if let Some(ref account_name) = config.local_account_name {
        let password = config.local_account_password.as_deref().unwrap_or("");
        let _ = write!(
            xml,
            r#"
            <UserAccounts>
                <LocalAccounts>
                    <LocalAccount wcm:action="add">
                        <Password><Value>{password}</Value><PlainText>true</PlainText></Password>
                        <Group>Administrators</Group>
                        <Name>{account_name}</Name>
                    </LocalAccount>
                </LocalAccounts>
            </UserAccounts>"#
        );
    }

    // -- Auto logon --
    if config.auto_logon
        && let Some(ref account_name) = config.local_account_name
    {
        let password = config.local_account_password.as_deref().unwrap_or("");
        let _ = write!(
            xml,
            r#"
            <AutoLogon>
                <Enabled>true</Enabled>
                <Username>{account_name}</Username>
                <Password><Value>{password}</Value><PlainText>true</PlainText></Password>
                <LogonCount>1</LogonCount>
            </AutoLogon>"#
        );
    }

    // -- First logon commands --
    // 1 built-in + N user commands; Cow avoids allocating for the static built-in.
    let mut first_logon_cmds: SmallVec<[Cow<'static, str>; 4]> = SmallVec::new();

    // Built-in: skip "Let's finish setting up" nag.
    if config.skip_finish_setup_nag {
        first_logon_cmds.push(Cow::Borrowed(
            r#"reg add "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\UserProfileEngagement" /v ScoobeSystemSettingEnabled /t REG_DWORD /d 0 /f"#
        ));
    }

    // User-provided first logon commands.
    for cmd in &config.first_logon_commands {
        first_logon_cmds.push(Cow::Owned(format!(
            "powershell -ExecutionPolicy Bypass -Command \"{cmd}\""
        )));
    }

    if !first_logon_cmds.is_empty() {
        xml.push_str("\n            <FirstLogonCommands>");
        for (i, cmd) in first_logon_cmds.iter().enumerate() {
            let _ = write!(
                xml,
                r#"
                <SynchronousCommand wcm:action="add">
                    <Order>{}</Order>
                    <CommandLine>{cmd}</CommandLine>
                </SynchronousCommand>"#,
                i + 1
            );
        }
        xml.push_str("\n            </FirstLogonCommands>");
    }

    xml.push_str(
        r#"
        </component>
    </settings>
</unattend>
"#,
    );

    xml
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Oobe;

    // -----------------------------------------------------------------------
    // generate_autounattend — basic structure
    // -----------------------------------------------------------------------

    #[test]
    fn xml_contains_xml_declaration() {
        let config = Oobe::default();
        let xml = generate_autounattend(&config);
        assert!(xml.starts_with("<?xml version=\"1.0\""));
    }

    #[test]
    fn xml_contains_unattend_root() {
        let config = Oobe::default();
        let xml = generate_autounattend(&config);
        assert!(xml.contains("<unattend"));
        assert!(xml.contains("</unattend>"));
    }

    #[test]
    fn xml_with_all_defaults_has_bypass_nro() {
        let config = Oobe::default(); // skip_microsoft_account = true
        let xml = generate_autounattend(&config);
        assert!(xml.contains("BypassNRO"));
        assert!(xml.contains("windowsPE"));
    }

    #[test]
    fn xml_without_ms_account_skip_has_no_bypass_nro() {
        let config = Oobe {
            inject_autounattend: true,
            skip_microsoft_account: false,
            skip_privacy_screens: true,
            skip_finish_setup_nag: true,
            ..Oobe::default()
        };
        let xml = generate_autounattend(&config);
        assert!(!xml.contains("BypassNRO"));
    }

    #[test]
    fn xml_with_privacy_screens_has_oobe_block() {
        let config = Oobe {
            inject_autounattend: true,
            skip_microsoft_account: false,
            skip_privacy_screens: true,
            skip_finish_setup_nag: true,
            ..Oobe::default()
        };
        let xml = generate_autounattend(&config);
        assert!(xml.contains("<OOBE>"));
        assert!(xml.contains("<ProtectYourPC>3</ProtectYourPC>"));
        assert!(xml.contains("<HideEULAPage>true</HideEULAPage>"));
        assert!(xml.contains("<HideWirelessSetupInOOBE>true</HideWirelessSetupInOOBE>"));
        assert!(xml.contains("<HideOnlineAccountScreens>true</HideOnlineAccountScreens>"));
        assert!(xml.contains("<HideOEMRegistrationScreen>true</HideOEMRegistrationScreen>"));
    }

    #[test]
    fn xml_without_privacy_screens_has_no_oobe_block() {
        let config = Oobe {
            inject_autounattend: true,
            skip_microsoft_account: false,
            skip_privacy_screens: false,
            skip_finish_setup_nag: true,
            ..Oobe::default()
        };
        let xml = generate_autounattend(&config);
        assert!(!xml.contains("<OOBE>"));
        assert!(!xml.contains("ProtectYourPC"));
    }

    #[test]
    fn xml_minimal_config() {
        let config = Oobe {
            inject_autounattend: true,
            skip_microsoft_account: false,
            skip_privacy_screens: false,
            skip_finish_setup_nag: false,
            bypass_tpm: false,
            bypass_secureboot: false,
            bypass_ram: false,
            disable_bitlocker: false,
            skip_auto_activation: false,
            ..Oobe::default()
        };
        let xml = generate_autounattend(&config);
        // Should still have the basic structure.
        assert!(xml.contains("<unattend"));
        assert!(xml.contains("oobeSystem"));
        assert!(!xml.contains("BypassNRO"));
        assert!(!xml.contains("<OOBE>"));
    }

    // -----------------------------------------------------------------------
    // inject_autounattend
    // -----------------------------------------------------------------------

    #[test]
    fn inject_creates_file() {
        let dir = tempfile::tempdir().unwrap();
        let config = Oobe::default();
        inject_autounattend(dir.path(), &config).unwrap();
        let path = dir.path().join("autounattend.xml");
        assert!(path.exists());
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("<?xml"));
    }

    #[test]
    fn inject_skipped_when_disabled() {
        let dir = tempfile::tempdir().unwrap();
        let config = Oobe {
            inject_autounattend: false,
            ..Oobe::default()
        };
        inject_autounattend(dir.path(), &config).unwrap();
        assert!(!dir.path().join("autounattend.xml").exists());
    }

    #[test]
    fn inject_overwrites_existing() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("autounattend.xml");
        std::fs::write(&path, "old content").unwrap();

        let config = Oobe::default();
        inject_autounattend(dir.path(), &config).unwrap();
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("<?xml"));
        assert!(!content.contains("old content"));
    }

    // -----------------------------------------------------------------------
    // Edge cases
    // -----------------------------------------------------------------------

    #[test]
    fn xml_all_features_enabled() {
        let config = Oobe {
            inject_autounattend: true,
            skip_microsoft_account: true,
            skip_privacy_screens: true,
            skip_finish_setup_nag: true,
            ..Oobe::default()
        };
        let xml = generate_autounattend(&config);
        assert!(xml.contains("BypassNRO"));
        assert!(xml.contains("<OOBE>"));
        assert!(xml.contains("ProtectYourPC"));
        assert!(xml.contains("HideEULAPage"));
        assert!(xml.contains("HideWirelessSetupInOOBE"));
        assert!(xml.contains("HideOnlineAccountScreens"));
        assert!(xml.contains("HideOEMRegistrationScreen"));
    }

    #[test]
    fn xml_all_features_disabled() {
        let config = Oobe {
            inject_autounattend: true,
            skip_microsoft_account: false,
            skip_privacy_screens: false,
            skip_finish_setup_nag: false,
            bypass_tpm: false,
            bypass_secureboot: false,
            bypass_ram: false,
            disable_bitlocker: false,
            skip_auto_activation: false,
            ..Oobe::default()
        };
        let xml = generate_autounattend(&config);
        assert!(!xml.contains("BypassNRO"));
        assert!(!xml.contains("<OOBE>"));
        // Still has the skeleton.
        assert!(xml.contains("<unattend"));
        assert!(xml.contains("oobeSystem"));
    }

    #[test]
    fn xml_bypass_nro_only() {
        let config = Oobe {
            inject_autounattend: true,
            skip_microsoft_account: true,
            skip_privacy_screens: false,
            skip_finish_setup_nag: false,
            bypass_tpm: false,
            bypass_secureboot: false,
            bypass_ram: false,
            disable_bitlocker: false,
            ..Oobe::default()
        };
        let xml = generate_autounattend(&config);
        assert!(xml.contains("BypassNRO"));
        assert!(!xml.contains("<OOBE>"));
    }

    #[test]
    fn xml_generated_by_wincrab_comment() {
        let config = Oobe::default();
        let xml = generate_autounattend(&config);
        assert!(xml.contains("Generated by wincrab"));
    }

    #[test]
    fn inject_to_nonexistent_dir_returns_error() {
        let config = Oobe::default();
        let result =
            inject_autounattend(std::path::Path::new("/nonexistent/dir/for/test"), &config);
        assert!(result.is_err());
    }

    #[test]
    fn xml_is_utf8() {
        let config = Oobe::default();
        let xml = generate_autounattend(&config);
        assert!(xml.contains("encoding=\"utf-8\""));
    }

    #[test]
    fn xml_angle_brackets_balanced() {
        let config = Oobe {
            inject_autounattend: true,
            skip_microsoft_account: true,
            skip_privacy_screens: true,
            skip_finish_setup_nag: true,
            ..Oobe::default()
        };
        let xml = generate_autounattend(&config);
        let open_count = xml.matches('<').count();
        let close_count = xml.matches('>').count();
        assert_eq!(open_count, close_count, "mismatched angle brackets");
    }

    // -----------------------------------------------------------------------
    // New feature tests: TPM/SecureBoot/RAM bypass
    // -----------------------------------------------------------------------

    #[test]
    fn xml_default_has_tpm_bypass() {
        let config = Oobe::default();
        let xml = generate_autounattend(&config);
        assert!(xml.contains("BypassTPMCheck"));
    }

    #[test]
    fn xml_default_has_secureboot_bypass() {
        let config = Oobe::default();
        let xml = generate_autounattend(&config);
        assert!(xml.contains("BypassSecureBootCheck"));
    }

    #[test]
    fn xml_default_has_ram_bypass() {
        let config = Oobe::default();
        let xml = generate_autounattend(&config);
        assert!(xml.contains("BypassRAMCheck"));
    }

    #[test]
    fn xml_no_tpm_bypass_when_disabled() {
        let config = Oobe {
            bypass_tpm: false,
            ..Oobe::default()
        };
        let xml = generate_autounattend(&config);
        assert!(!xml.contains("BypassTPMCheck"));
    }

    #[test]
    fn xml_no_secureboot_bypass_when_disabled() {
        let config = Oobe {
            bypass_secureboot: false,
            ..Oobe::default()
        };
        let xml = generate_autounattend(&config);
        assert!(!xml.contains("BypassSecureBootCheck"));
    }

    #[test]
    fn xml_no_ram_bypass_when_disabled() {
        let config = Oobe {
            bypass_ram: false,
            ..Oobe::default()
        };
        let xml = generate_autounattend(&config);
        assert!(!xml.contains("BypassRAMCheck"));
    }

    // -----------------------------------------------------------------------
    // New feature tests: BitLocker
    // -----------------------------------------------------------------------

    #[test]
    fn xml_default_has_bitlocker_disable() {
        let config = Oobe::default();
        let xml = generate_autounattend(&config);
        assert!(xml.contains("PreventDeviceEncryption"));
    }

    #[test]
    fn xml_no_bitlocker_disable_when_off() {
        let config = Oobe {
            disable_bitlocker: false,
            ..Oobe::default()
        };
        let xml = generate_autounattend(&config);
        assert!(!xml.contains("PreventDeviceEncryption"));
    }

    // -----------------------------------------------------------------------
    // New feature tests: Product key
    // -----------------------------------------------------------------------

    #[test]
    fn xml_with_product_key() {
        let config = Oobe {
            product_key: Some("VK7JG-NPHTM-C97JM-9MPGT-3V66T".into()),
            ..Oobe::default()
        };
        let xml = generate_autounattend(&config);
        assert!(xml.contains("<ProductKey>"));
        assert!(xml.contains("VK7JG-NPHTM-C97JM-9MPGT-3V66T"));
    }

    #[test]
    fn xml_no_product_key_by_default() {
        let config = Oobe::default();
        let xml = generate_autounattend(&config);
        assert!(!xml.contains("<ProductKey>"));
    }

    // -----------------------------------------------------------------------
    // New feature tests: Auto partition
    // -----------------------------------------------------------------------

    #[test]
    fn xml_with_auto_partition() {
        let config = Oobe {
            auto_partition: true,
            ..Oobe::default()
        };
        let xml = generate_autounattend(&config);
        assert!(xml.contains("<DiskConfiguration>"));
        assert!(xml.contains("<WillWipeDisk>true</WillWipeDisk>"));
        assert!(xml.contains("<Type>EFI</Type>"));
        assert!(xml.contains("<Type>MSR</Type>"));
        assert!(xml.contains("<Type>Primary</Type>"));
        assert!(xml.contains("<ImageInstall>"));
        assert!(xml.contains("<PartitionID>3</PartitionID>"));
    }

    #[test]
    fn xml_no_auto_partition_by_default() {
        let config = Oobe::default();
        let xml = generate_autounattend(&config);
        assert!(!xml.contains("<DiskConfiguration>"));
        assert!(!xml.contains("<ImageInstall>"));
    }

    // -----------------------------------------------------------------------
    // New feature tests: specialize pass
    // -----------------------------------------------------------------------

    #[test]
    fn xml_with_computer_name() {
        let config = Oobe {
            computer_name: Some("MYPC".into()),
            ..Oobe::default()
        };
        let xml = generate_autounattend(&config);
        assert!(xml.contains("specialize"));
        assert!(xml.contains("<ComputerName>MYPC</ComputerName>"));
    }

    #[test]
    fn xml_with_wildcard_computer_name() {
        let config = Oobe {
            computer_name: Some("*".into()),
            ..Oobe::default()
        };
        let xml = generate_autounattend(&config);
        assert!(xml.contains("<ComputerName>*</ComputerName>"));
    }

    #[test]
    fn xml_with_timezone() {
        let config = Oobe {
            timezone: Some("Pacific Standard Time".into()),
            ..Oobe::default()
        };
        let xml = generate_autounattend(&config);
        assert!(xml.contains("specialize"));
        assert!(xml.contains("<TimeZone>Pacific Standard Time</TimeZone>"));
    }

    #[test]
    fn xml_skip_auto_activation() {
        let config = Oobe::default(); // skip_auto_activation = true by default
        let xml = generate_autounattend(&config);
        assert!(xml.contains("specialize"));
        assert!(xml.contains("<SkipAutoActivation>true</SkipAutoActivation>"));
        assert!(xml.contains("Microsoft-Windows-Security-SPP-UX"));
    }

    #[test]
    fn xml_no_specialize_when_nothing_set() {
        let config = Oobe {
            computer_name: None,
            timezone: None,
            skip_auto_activation: false,
            ..Oobe::default()
        };
        let xml = generate_autounattend(&config);
        assert!(!xml.contains("specialize"));
    }

    // -----------------------------------------------------------------------
    // New feature tests: Local account
    // -----------------------------------------------------------------------

    #[test]
    fn xml_with_local_account() {
        let config = Oobe {
            local_account_name: Some("User".into()),
            ..Oobe::default()
        };
        let xml = generate_autounattend(&config);
        assert!(xml.contains("<UserAccounts>"));
        assert!(xml.contains("<LocalAccounts>"));
        assert!(xml.contains("<Name>User</Name>"));
        assert!(xml.contains("<Group>Administrators</Group>"));
    }

    #[test]
    fn xml_with_local_account_and_password() {
        let config = Oobe {
            local_account_name: Some("Admin".into()),
            local_account_password: Some("secret123".into()),
            ..Oobe::default()
        };
        let xml = generate_autounattend(&config);
        assert!(xml.contains("<Name>Admin</Name>"));
        assert!(xml.contains("<Value>secret123</Value>"));
    }

    #[test]
    fn xml_local_account_empty_password_by_default() {
        let config = Oobe {
            local_account_name: Some("User".into()),
            ..Oobe::default()
        };
        let xml = generate_autounattend(&config);
        assert!(xml.contains("<Value></Value>"));
    }

    #[test]
    fn xml_no_local_account_by_default() {
        let config = Oobe::default();
        let xml = generate_autounattend(&config);
        assert!(!xml.contains("<UserAccounts>"));
        assert!(!xml.contains("<LocalAccounts>"));
    }

    // -----------------------------------------------------------------------
    // New feature tests: Auto logon
    // -----------------------------------------------------------------------

    #[test]
    fn xml_with_auto_logon() {
        let config = Oobe {
            local_account_name: Some("User".into()),
            auto_logon: true,
            ..Oobe::default()
        };
        let xml = generate_autounattend(&config);
        assert!(xml.contains("<AutoLogon>"));
        assert!(xml.contains("<Enabled>true</Enabled>"));
        assert!(xml.contains("<Username>User</Username>"));
        assert!(xml.contains("<LogonCount>1</LogonCount>"));
    }

    #[test]
    fn xml_auto_logon_without_account_name_has_no_autologon() {
        let config = Oobe {
            auto_logon: true,
            local_account_name: None,
            ..Oobe::default()
        };
        let xml = generate_autounattend(&config);
        assert!(!xml.contains("<AutoLogon>"));
    }

    #[test]
    fn xml_no_auto_logon_by_default() {
        let config = Oobe::default();
        let xml = generate_autounattend(&config);
        assert!(!xml.contains("<AutoLogon>"));
    }

    // -----------------------------------------------------------------------
    // New feature tests: First logon commands
    // -----------------------------------------------------------------------

    #[test]
    fn xml_with_first_logon_commands() {
        let config = Oobe {
            first_logon_commands: vec![
                "Set-ExecutionPolicy RemoteSigned".into(),
                "Install-Module PSReadLine".into(),
            ],
            ..Oobe::default()
        };
        let xml = generate_autounattend(&config);
        assert!(xml.contains("<FirstLogonCommands>"));
        assert!(xml.contains("Set-ExecutionPolicy RemoteSigned"));
        assert!(xml.contains("Install-Module PSReadLine"));
        assert!(xml.contains("powershell -ExecutionPolicy Bypass -Command"));
    }

    #[test]
    fn xml_first_logon_commands_include_finish_setup_nag() {
        let config = Oobe {
            skip_finish_setup_nag: true,
            ..Oobe::default()
        };
        let xml = generate_autounattend(&config);
        assert!(xml.contains("<FirstLogonCommands>"));
        assert!(xml.contains("ScoobeSystemSettingEnabled"));
    }

    #[test]
    fn xml_first_logon_commands_order_sequential() {
        let config = Oobe {
            skip_finish_setup_nag: true,
            first_logon_commands: vec!["Get-Date".into()],
            ..Oobe::default()
        };
        let xml = generate_autounattend(&config);
        assert!(xml.contains("<Order>1</Order>"));
        assert!(xml.contains("<Order>2</Order>"));
    }

    #[test]
    fn xml_no_first_logon_commands_when_empty_and_no_nag() {
        let config = Oobe {
            skip_finish_setup_nag: false,
            first_logon_commands: vec![],
            ..Oobe::default()
        };
        let xml = generate_autounattend(&config);
        assert!(!xml.contains("<FirstLogonCommands>"));
    }

    // -----------------------------------------------------------------------
    // Full config test
    // -----------------------------------------------------------------------

    #[test]
    fn xml_full_config_all_features() {
        let config = Oobe {
            inject_autounattend: true,
            skip_microsoft_account: true,
            skip_privacy_screens: true,
            skip_finish_setup_nag: true,
            bypass_tpm: true,
            bypass_secureboot: true,
            bypass_ram: true,
            timezone: Some("UTC".into()),
            local_account_name: Some("Admin".into()),
            local_account_password: Some("pass".into()),
            auto_logon: true,
            disable_bitlocker: true,
            computer_name: Some("WINCRAB-PC".into()),
            product_key: Some("XXXXX-XXXXX-XXXXX-XXXXX-XXXXX".into()),
            first_logon_commands: vec!["echo hello".into()],
            convert_edition: None,
            skip_auto_activation: true,
            auto_partition: true,
        };
        let xml = generate_autounattend(&config);

        // windowsPE pass
        assert!(xml.contains("windowsPE"));
        assert!(xml.contains("BypassNRO"));
        assert!(xml.contains("BypassTPMCheck"));
        assert!(xml.contains("BypassSecureBootCheck"));
        assert!(xml.contains("BypassRAMCheck"));
        assert!(xml.contains("PreventDeviceEncryption"));
        assert!(xml.contains("XXXXX-XXXXX-XXXXX-XXXXX-XXXXX"));
        assert!(xml.contains("<DiskConfiguration>"));

        // specialize pass
        assert!(xml.contains("specialize"));
        assert!(xml.contains("<ComputerName>WINCRAB-PC</ComputerName>"));
        assert!(xml.contains("<TimeZone>UTC</TimeZone>"));
        assert!(xml.contains("<SkipAutoActivation>true</SkipAutoActivation>"));

        // oobeSystem pass
        assert!(xml.contains("oobeSystem"));
        assert!(xml.contains("<OOBE>"));
        assert!(xml.contains("<Name>Admin</Name>"));
        assert!(xml.contains("<Value>pass</Value>"));
        assert!(xml.contains("<AutoLogon>"));
        assert!(xml.contains("<Username>Admin</Username>"));
        assert!(xml.contains("<FirstLogonCommands>"));
        assert!(xml.contains("echo hello"));
    }

    #[test]
    fn xml_full_config_angle_brackets_balanced() {
        let config = Oobe {
            inject_autounattend: true,
            skip_microsoft_account: true,
            skip_privacy_screens: true,
            skip_finish_setup_nag: true,
            bypass_tpm: true,
            bypass_secureboot: true,
            bypass_ram: true,
            timezone: Some("UTC".into()),
            local_account_name: Some("User".into()),
            local_account_password: None,
            auto_logon: true,
            disable_bitlocker: true,
            computer_name: Some("*".into()),
            product_key: Some("KEY".into()),
            first_logon_commands: vec!["cmd1".into(), "cmd2".into()],
            convert_edition: None,
            skip_auto_activation: true,
            auto_partition: true,
        };
        let xml = generate_autounattend(&config);
        let open_count = xml.matches('<').count();
        let close_count = xml.matches('>').count();
        assert_eq!(
            open_count, close_count,
            "mismatched angle brackets in full config XML"
        );
    }
}
