use std::path::Path;

use tracing::info;

use crate::config::Performance;
use crate::error::{ensure_dir, write_file, Error};

pub fn generate_performance_script(config: &Performance) -> String {
    let mut script = String::new();
    script.push_str("# wincrab performance tweaks\n");
    script.push_str("# This script is generated by wincrab and runs on first boot.\n\n");

    if config.high_perf_power_plan {
        script.push_str("# Set High Performance power plan\n");
        script.push_str("powercfg /setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c\n\n");
    }

    script
}

pub fn inject_performance_script(
    mount_dir: &Path,
    config: &Performance,
) -> Result<(), Error> {
    if !config.high_perf_power_plan {
        return Ok(());
    }

    let script = generate_performance_script(config);

    let script_dir = mount_dir.join("wincrab");
    ensure_dir(&script_dir)?;

    let script_path = script_dir.join("performance.ps1");
    write_file(&script_path, &script)?;

    info!(path = %script_path.display(), "injected performance script");

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn script_contains_power_plan_when_enabled() {
        let config = Performance {
            high_perf_power_plan: true,
            ..Performance::default()
        };
        let script = generate_performance_script(&config);
        assert!(script.contains("powercfg /setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c"));
    }

    #[test]
    fn script_omits_power_plan_when_disabled() {
        let config = Performance {
            high_perf_power_plan: false,
            ..Performance::default()
        };
        let script = generate_performance_script(&config);
        assert!(!script.contains("powercfg"));
    }

    #[test]
    fn inject_skips_when_no_features() {
        let dir = tempfile::tempdir().unwrap();
        let config = Performance {
            high_perf_power_plan: false,
            ..Performance::default()
        };
        inject_performance_script(dir.path(), &config).unwrap();
        assert!(!dir.path().join("wincrab/performance.ps1").exists());
    }

    #[test]
    fn inject_writes_script_file() {
        let dir = tempfile::tempdir().unwrap();
        let config = Performance {
            high_perf_power_plan: true,
            ..Performance::default()
        };
        inject_performance_script(dir.path(), &config).unwrap();

        let script_path = dir.path().join("wincrab/performance.ps1");
        assert!(script_path.exists());
        let content = std::fs::read_to_string(&script_path).unwrap();
        assert!(content.contains("powercfg"));
    }
}
