use std::path::{Path, PathBuf};

use tracing::info;

use crate::config::Seelen;
use crate::error::{copy_file, ensure_dir, write_file, Error};
use crate::github::{self, GitHubAsset};

const GITHUB_API_LATEST: &str =
    "https://api.github.com/repos/eythaann/Seelen-UI/releases/latest";

/// Asset descriptor for the Seelen-UI x64 setup executable.
struct SeelenRelease;

impl GitHubAsset for SeelenRelease {
    fn api_url(&self) -> &str {
        GITHUB_API_LATEST
    }

    fn label(&self) -> &str {
        "Seelen-UI"
    }

    fn output_filename(&self) -> Option<&str> {
        Some("Seelen.UI-setup.exe")
    }

    fn match_priority(&self, url: &str) -> u32 {
        if url.contains("x64-setup.exe") && !url.contains("fixed") {
            2
        } else if url.contains("x64-setup") && url.ends_with(".exe") {
            1
        } else {
            0
        }
    }
}

/// Download the Seelen-UI setup executable from GitHub releases.
///
/// Caches the download in `work_dir` so repeated runs skip the download.
/// Returns the path to the downloaded setup.exe, or `None` if bundling is
/// disabled.
pub fn download_seelen(work_dir: &Path, config: &Seelen) -> Result<Option<PathBuf>, Error> {
    if !config.bundle {
        return Ok(None);
    }

    let cache_dir = work_dir.join("seelen-cache");
    let path = github::download_asset(&SeelenRelease, &cache_dir)?;
    Ok(Some(path))
}

/// Inject Seelen-UI into the mounted WIM image and create a first-boot
/// install script.
pub fn inject_seelen(
    mount_dir: &Path,
    setup_exe: &Path,
    config: &Seelen,
) -> Result<(), Error> {
    let dest_dir = mount_dir.join("SeelenUI");
    ensure_dir(&dest_dir)?;

    let dest_exe = dest_dir.join("Seelen.UI-setup.exe");
    info!(
        src = %setup_exe.display(),
        dest = %dest_exe.display(),
        "copying Seelen-UI setup into WIM"
    );
    copy_file(setup_exe, &dest_exe)?;

    let script = generate_install_script(config);
    let script_path = dest_dir.join("install.ps1");
    info!(path = %script_path.display(), "writing first-boot install script");
    write_file(&script_path, &script)?;

    Ok(())
}

/// Generate a PowerShell script that installs Seelen-UI on first boot.
fn generate_install_script(config: &Seelen) -> String {
    let shell_replacement = if config.replace_shell {
        r#"
# Set Seelen-UI as the Windows shell (replaces explorer.exe taskbar/start).
# The Seelen-UI executable path after installation.
$seelenExe = "$env:ProgramFiles\Seelen-UI\seelen-ui.exe"
if (Test-Path $seelenExe) {
    Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name 'Shell' -Value $seelenExe
    Write-Host "Seelen-UI set as Windows shell."
} else {
    # Fallback: look for the user-installed location
    $userSeelen = "$env:LOCALAPPDATA\Programs\Seelen-UI\seelen-ui.exe"
    if (Test-Path $userSeelen) {
        Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name 'Shell' -Value $userSeelen
        Write-Host "Seelen-UI (user install) set as Windows shell."
    } else {
        Write-Host "WARNING: Seelen-UI executable not found, keeping explorer.exe as shell."
    }
}
"#
    } else {
        ""
    };

    format!(
        r#"# Seelen-UI First-Boot Installer
# Generated by wincrab -- do not edit.
# This script runs once on first user login via RunOnce registry key.

$ErrorActionPreference = 'Stop'
$setupExe = 'C:\SeelenUI\Seelen.UI-setup.exe'

Write-Host "Installing Seelen-UI..."

# Run the installer silently. The Seelen-UI .exe installer (NSIS-based)
# supports /S for silent mode.
Start-Process -FilePath $setupExe -ArgumentList '/S' -Wait -NoNewWindow
Write-Host "Seelen-UI installation complete."
{shell_replacement}
# Clean up the installer directory.
Remove-Item -Path 'C:\SeelenUI' -Recurse -Force -ErrorAction SilentlyContinue
Write-Host "Installer cleanup done."
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Seelen;

    // -----------------------------------------------------------------------
    // SeelenRelease::match_priority
    // -----------------------------------------------------------------------

    #[test]
    fn match_priority_prefers_non_fixed() {
        assert_eq!(
            SeelenRelease.match_priority(
                "https://example.com/Seelen.UI_2.5.3_x64-setup.exe"
            ),
            2
        );
        assert_eq!(
            SeelenRelease.match_priority(
                "https://example.com/Seelen.UI_2.5.3_x64-setup-fixed.exe"
            ),
            1
        );
    }

    #[test]
    fn match_priority_rejects_non_x64() {
        assert_eq!(
            SeelenRelease.match_priority(
                "https://example.com/Seelen.UI_2.5.3_arm64-setup.exe"
            ),
            0
        );
    }

    #[test]
    fn match_priority_rejects_non_exe() {
        assert_eq!(
            SeelenRelease.match_priority("https://example.com/source.tar.gz"),
            0
        );
    }

    // -----------------------------------------------------------------------
    // select_asset_url integration (via SeelenRelease)
    // -----------------------------------------------------------------------

    const SAMPLE_JSON: &str = r#"
{
  "tag_name": "v2.5.3",
  "assets": [
    {
      "name": "Seelen.UI_2.5.3_x64-setup.exe",
      "browser_download_url": "https://github.com/eythaann/Seelen-UI/releases/download/v2.5.3/Seelen.UI_2.5.3_x64-setup.exe"
    },
    {
      "name": "Seelen.UI_2.5.3_arm64-setup.exe",
      "browser_download_url": "https://github.com/eythaann/Seelen-UI/releases/download/v2.5.3/Seelen.UI_2.5.3_arm64-setup.exe"
    },
    {
      "name": "source.tar.gz",
      "browser_download_url": "https://github.com/eythaann/Seelen-UI/archive/refs/tags/v2.5.3.tar.gz"
    }
  ]
}
"#;

    fn select_seelen(json: &str) -> Result<String, crate::Error> {
        crate::github::select_asset_url(json, "Seelen-UI", |u| SeelenRelease.match_priority(u))
    }

    #[test]
    fn select_finds_x64_setup() {
        let url = select_seelen(SAMPLE_JSON).unwrap();
        assert!(url.contains("x64-setup.exe"));
        assert!(!url.contains("arm64"));
    }

    #[test]
    fn select_prefers_non_fixed_variant() {
        let json = r#"
    "browser_download_url": "https://example.com/Seelen.UI_2.5.3_x64-setup-fixed.exe"
    "browser_download_url": "https://example.com/Seelen.UI_2.5.3_x64-setup.exe"
"#;
        let url = select_seelen(json).unwrap();
        assert!(!url.contains("fixed"));
    }

    #[test]
    fn select_falls_back_to_fixed() {
        let json = r#"
    "browser_download_url": "https://example.com/Seelen.UI_2.5.3_x64-setup-fixed.exe"
"#;
        let url = select_seelen(json).unwrap();
        assert!(url.contains("fixed"));
    }

    #[test]
    fn select_no_match_returns_error() {
        let json = r#"
    "browser_download_url": "https://example.com/something_arm64.tar.gz"
"#;
        assert!(select_seelen(json).is_err());
    }

    #[test]
    fn select_empty_json() {
        assert!(select_seelen("").is_err());
    }

    #[test]
    fn select_handles_trailing_comma() {
        let json =
            r#"      "browser_download_url": "https://example.com/Seelen.UI_1.0_x64-setup.exe","#;
        let url = select_seelen(json).unwrap();
        assert_eq!(url, "https://example.com/Seelen.UI_1.0_x64-setup.exe");
    }

    // -----------------------------------------------------------------------
    // generate_install_script
    // -----------------------------------------------------------------------

    #[test]
    fn script_contains_silent_install() {
        let config = Seelen::default();
        let script = generate_install_script(&config);
        assert!(script.contains("/S"));
        assert!(script.contains("Start-Process"));
    }

    #[test]
    fn script_with_shell_replacement() {
        let config = Seelen {
            bundle: true,
            replace_shell: true,
            ..Default::default()
        };
        let script = generate_install_script(&config);
        assert!(script.contains("Winlogon"));
        assert!(script.contains("Shell"));
        assert!(script.contains("seelen-ui.exe"));
    }

    #[test]
    fn script_without_shell_replacement() {
        let config = Seelen {
            bundle: true,
            replace_shell: false,
            ..Default::default()
        };
        let script = generate_install_script(&config);
        assert!(!script.contains("Winlogon"));
    }

    #[test]
    fn script_cleanup_section() {
        let config = Seelen::default();
        let script = generate_install_script(&config);
        assert!(script.contains("Remove-Item"));
        assert!(script.contains("SeelenUI"));
    }

    #[test]
    fn script_header() {
        let config = Seelen::default();
        let script = generate_install_script(&config);
        assert!(script.contains("$ErrorActionPreference = 'Stop'"));
        assert!(script.contains("Generated by wincrab"));
    }

    // -----------------------------------------------------------------------
    // inject_seelen
    // -----------------------------------------------------------------------

    #[test]
    fn inject_seelen_creates_files() {
        let dir = tempfile::tempdir().unwrap();
        let mount = dir.path().join("mount");
        std::fs::create_dir_all(&mount).unwrap();

        let setup_exe = dir.path().join("setup.exe");
        std::fs::write(&setup_exe, b"MZ fake exe").unwrap();

        let config = Seelen::default();
        inject_seelen(&mount, &setup_exe, &config).unwrap();

        assert!(mount.join("SeelenUI").join("Seelen.UI-setup.exe").exists());
        assert!(mount.join("SeelenUI").join("install.ps1").exists());

        let copied = std::fs::read(mount.join("SeelenUI/Seelen.UI-setup.exe")).unwrap();
        assert_eq!(copied, b"MZ fake exe");

        let script = std::fs::read_to_string(mount.join("SeelenUI/install.ps1")).unwrap();
        assert!(script.contains("Installing Seelen-UI"));
    }

    // -----------------------------------------------------------------------
    // download_seelen
    // -----------------------------------------------------------------------

    #[test]
    fn download_seelen_returns_none_when_disabled() {
        let dir = tempfile::tempdir().unwrap();
        let config = Seelen {
            bundle: false,
            ..Default::default()
        };
        let result = download_seelen(dir.path(), &config).unwrap();
        assert!(result.is_none());
    }

    #[test]
    fn download_seelen_uses_cache() {
        let dir = tempfile::tempdir().unwrap();
        let cache = dir.path().join("seelen-cache");
        std::fs::create_dir_all(&cache).unwrap();
        std::fs::write(cache.join("Seelen.UI-setup.exe"), b"cached").unwrap();

        let config = Seelen {
            bundle: true,
            ..Default::default()
        };
        let result = download_seelen(dir.path(), &config).unwrap();
        assert!(result.is_some());
        assert!(result.unwrap().ends_with("Seelen.UI-setup.exe"));
    }
}
